--------------------------------------------------------
--  Datei erstellt -Dienstag-Juli-19-2011   
--------------------------------------------------------
-- Wiedergabe von TABLE DDL für Objekt DBO.HP_PART_ORDER_DM nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.HPOD_IDX1_SUBC_ID ON DBO.HP_PART_ORDER_DM (SUBCASE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.HPOD_IDX2_CASE_ID ON DBO.HP_PART_ORDER_DM (CASE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)CREATE TABLE DBO.HP_PART_ORDER_DM 
(
  HP_PART_ORDER_ID NUMBER(10, 0) NOT NULL 
, SUBCASE_ID VARCHAR2(90 BYTE) NOT NULL 
, CASE_ID VARCHAR2(90 BYTE) 
, X_ADDRESS_TYPE_CD NUMBER(10, 0) 
, X_ORDER_ID VARCHAR2(120 BYTE) 
, X_ORDER_NUMBER VARCHAR2(120 BYTE) 
, X_PART_ORDER_ETA DATE 
, X_PART_ORDER_TYPE VARCHAR2(60 BYTE) 
, X_PICK_PACK_INSTRUCTIONS VARCHAR2(765 BYTE) 
, X_RECEIVED_INSTRUCTIONS VARCHAR2(765 BYTE) 
, X_REQUESTED_ETA DATE 
, X_SENT_INSTRUCTIONS VARCHAR2(765 BYTE) 
, X_SHIP_ADDRESS VARCHAR2(600 BYTE) 
, X_SHIP_ADDRESS2 VARCHAR2(600 BYTE) 
, X_SHIP_CITY VARCHAR2(90 BYTE) 
, X_SHIP_COUNTRY VARCHAR2(120 BYTE) 
, X_SHIP_STATE VARCHAR2(120 BYTE) 
, X_SHIP_ZIPCODE VARCHAR2(60 BYTE) 
, X_COMPANY_NAME VARCHAR2(240 BYTE) 
, X_LOGISTICS_SYSTEM VARCHAR2(60 BYTE) 
, X_CONTACT_ALT_PHONE VARCHAR2(75 BYTE) 
, X_CONTACT_FIRST_NAME VARCHAR2(90 BYTE) 
, X_CONTACT_LAST_NAME VARCHAR2(90 BYTE) 
, X_CONTACT_PHONE VARCHAR2(75 BYTE) 
, X_LAST_MOD_TIME DATE 
, X_LOGGING_TYPE_CD VARCHAR2(12 BYTE) 
, X_PARTIAL_ORDER_FLAG NUMBER(10, 0) 
, X_LOGISTICS_CENTER VARCHAR2(30 BYTE) 
, X_LOGISTICS_CENTER_PHONE VARCHAR2(75 BYTE) 
, X_SERVICE_NOTIFICATION_NUMBER VARCHAR2(36 BYTE) 
, X_ORDER_TYPE VARCHAR2(60 BYTE) 
, X_CREATION_TIME DATE 
, X_SERVICE_NOTE_NUMBER VARCHAR2(60 BYTE) 
, DATE_ADDED DATE 
, DATE_MODIFIED DATE 
, SHIP_METHOD VARCHAR2(240 BYTE) 
, DELIVERY_PRIORITY VARCHAR2(240 BYTE) 
, X_SHIP_ISO_COUNTRY_CODE VARCHAR2(6 BYTE) 
, X_CONTACT_FAX_NUMBER VARCHAR2(60 BYTE) 
, X_RESERVED_FLAG NUMBER(1, 0) 
, HP_PART_ORDER2CC_DLVR_PRIOR NUMBER(10, 0) 
, HP_PART_ORDER2CC_SHIP_METHOD NUMBER(10, 0) 
, HP_PART_ORDER_REASON VARCHAR2(240 BYTE) 
, X_SHIP_MTHD_UPG_RSN VARCHAR2(60 BYTE) 
, RESPONSIBLE_EMPLOYEE_ID NUMBER(10, 0) 
, CONSTRAINT HPOD_PK PRIMARY KEY 
  (
    HP_PART_ORDER_ID 
  )
  ENABLE 
) 
NOLOGGING 
TABLESPACE "WFMTABMED" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 4194304 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.HPOD_IDX1_SUBC_ID nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.HPOD_IDX1_SUBC_ID ON DBO.HP_PART_ORDER_DM (SUBCASE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.HPOD_IDX2_CASE_ID nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.HPOD_IDX2_CASE_ID ON DBO.HP_PART_ORDER_DM (CASE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.HPOD_PK nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE UNIQUE INDEX DBO.HPOD_PK ON DBO.HP_PART_ORDER_DM (HP_PART_ORDER_ID) 
NOLOGGING 
TABLESPACE "WFMIDXMED" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 4194304 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
