--------------------------------------------------------
--  Datei erstellt -Dienstag-Juli-19-2011   
--------------------------------------------------------
-- Wiedergabe von TABLE DDL für Objekt DBO.HP_SV_DLVR_DM nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.HSDD_IDX1_CASE_ID ON DBO.HP_SV_DLVR_DM (CASE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.HSDD_IDX2_SUBCASE_ID ON DBO.HP_SV_DLVR_DM (SUBCASE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)CREATE TABLE DBO.HP_SV_DLVR_DM 
(
  HP_SV_DLVR_ID NUMBER(10, 0) NOT NULL 
, CASE_ID VARCHAR2(90 BYTE) NOT NULL 
, SUBCASE_ID VARCHAR2(90 BYTE) 
, X_DUE_DATE DATE 
, X_SERVICE_LOCATION VARCHAR2(240 BYTE) 
, X_ADDRESS VARCHAR2(600 BYTE) 
, X_ADDRESS_2 VARCHAR2(600 BYTE) 
, X_CITY VARCHAR2(90 BYTE) 
, X_STATE VARCHAR2(120 BYTE) 
, X_ZIPCODE VARCHAR2(60 BYTE) 
, X_ISO_COUNTRY_CODE VARCHAR2(6 BYTE) 
, X_EARLIEST_START_TIME DATE 
, X_CONTACT_PHONE VARCHAR2(75 BYTE) 
, BUSINESS_CENTER_NAME VARCHAR2(192 BYTE) 
, REGION VARCHAR2(192 BYTE) 
, DISTRICT VARCHAR2(192 BYTE) 
, ENGINEER_FIRST_NAME VARCHAR2(90 BYTE) 
, ENGINEER_LAST_NAME VARCHAR2(90 BYTE) 
, TIMEZONE_ID NUMBER(10, 0) 
, DATE_ADDED DATE 
, DATE_MODIFIED DATE 
, X_CE_ACKNOWLEDGE_FLAG NUMBER(10, 0) 
, X_CONTACT_FIRST_NAME VARCHAR2(90 BYTE) 
, X_CONTACT_LAST_NAME VARCHAR2(90 BYTE) 
, CE_STATUS VARCHAR2(240 BYTE) 
, X_ESTIMATED_TASK_DURATION NUMBER(10, 0) 
, X_CSR_REFUSED_REASON VARCHAR2(60 BYTE) 
, X_NLS_CSR_REFUSED_REASON VARCHAR2(120 BYTE) 
, X_CONTACT_ALT_PHONE VARCHAR2(75 BYTE) 
, X_CONTACT_EMAIL VARCHAR2(240 BYTE) 
, X_CONTACT_PREF_LANG VARCHAR2(60 BYTE) 
, X_ALT_CONTACT_FIRST_NAME VARCHAR2(90 BYTE) 
, X_ALT_CONTACT_LAST_NAME VARCHAR2(90 BYTE) 
, X_ALT_CONTACT_PHONE VARCHAR2(75 BYTE) 
, X_ALT_CONTACT_ALT_PHONE VARCHAR2(75 BYTE) 
, X_ALT_CONTACT_EMAIL VARCHAR2(240 BYTE) 
, X_ALT_CONTACT_PREF_LANG VARCHAR2(60 BYTE) 
, X_CONTACT_EDITED_FLAG NUMBER 
, X_DEPARTMENT VARCHAR2(120 BYTE) 
, X_NO_AUTO_DISPATCH_FLAG NUMBER 
, X_CONTACT_SURVEY_FLAG NUMBER 
, FIRST_HP_SKILL_REF_ID NUMBER 
, ACTIVITY_LOG_ID NUMBER 
, CONSTRAINT HSDD_PK PRIMARY KEY 
  (
    HP_SV_DLVR_ID 
  )
  ENABLE 
) 
NOLOGGING 
TABLESPACE "WFMTABMED" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 4194304 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.HSDD_PK nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE UNIQUE INDEX DBO.HSDD_PK ON DBO.HP_SV_DLVR_DM (HP_SV_DLVR_ID) 
NOLOGGING 
TABLESPACE "WFMIDXMED" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 4194304 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.HSDD_IDX1_CASE_ID nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.HSDD_IDX1_CASE_ID ON DBO.HP_SV_DLVR_DM (CASE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.HSDD_IDX2_SUBCASE_ID nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.HSDD_IDX2_SUBCASE_ID ON DBO.HP_SV_DLVR_DM (SUBCASE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
