--------------------------------------------------------
--  Datei erstellt -Dienstag-Juli-19-2011   
--------------------------------------------------------
-- Wiedergabe von TABLE DDL für Objekt DBO.NOTES_LOG_DM nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.NLD_IDX1_DATE_ADDED ON DBO.NOTES_LOG_DM (DATE_ADDED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.NLD_IDX2_DATE_EMPLOYEE_ID ON DBO.NOTES_LOG_DM (EMPLOYEE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.NLD_IDX3_DATE_ACTION_TYPE ON DBO.NOTES_LOG_DM (ACTION_TYPE ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.NLD_IDX4_CASE_ID ON DBO.NOTES_LOG_DM (CASE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.NLD_IDX5_ACCOUNTABILITY_ID ON DBO.NOTES_LOG_DM (ACCOUNTABILITY_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)CREATE TABLE DBO.NOTES_LOG_DM 
(
  ACCOUNTABILITY_ID VARCHAR2(90 BYTE) 
, CREATE_DATE DATE NOT NULL 
, ACTION_TYPE VARCHAR2(120 BYTE) NOT NULL 
, EMPLOYEE_ID NUMBER NOT NULL 
, CASE_ID VARCHAR2(90 BYTE) NOT NULL 
, CASE_SUBCASE VARCHAR2(30 BYTE) 
, WORK_GROUP VARCHAR2(240 BYTE) 
, DATE_ADDED DATE 
, INTERNAL VARCHAR2(765 BYTE) 
, NOTES VARCHAR2(4000 BYTE) 
, NLS_ACTION_TYPE VARCHAR2(240 BYTE) 
, COMMITMENT VARCHAR2(240 BYTE) 
, NOTES_LOG_ID NUMBER(10, 0) NOT NULL 
, CONSTRAINT NLD_PK PRIMARY KEY 
  (
    NOTES_LOG_ID 
  , CASE_ID 
  )
  ENABLE 
) 
NOLOGGING 
TABLESPACE "WFMTABLAR" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von TABLE DDL für Objekt DBO.ONSITE_LOG_DM nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.OLD_IDX1_DATE_MODIFIED ON DBO.ONSITE_LOG_DM (DATE_MODIFIED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.OLD_IDX2_CASE_ID ON DBO.ONSITE_LOG_DM (CASE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.OLD_IDX3_ACCOUNTABILITY_ID ON DBO.ONSITE_LOG_DM (ACCOUNTABILITY_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.OLD_IDX4_EMPLOYEE_TABLE_ID ON DBO.ONSITE_LOG_DM (EMPLOYEE_TABLE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)CREATE TABLE DBO.ONSITE_LOG_DM 
(
  ONSITE_LOG_ID NUMBER(10, 0) NOT NULL 
, ACCOUNTABILITY_ID VARCHAR2(90 BYTE) 
, CASE_ID VARCHAR2(90 BYTE) 
, CASE_SUBCASE VARCHAR2(30 BYTE) 
, CREATION_TIME DATE 
, EMPLOYEE_TABLE_ID NUMBER(10, 0) NOT NULL 
, WORK_GROUP VARCHAR2(240 BYTE) 
, X_BILLABLE_OVERTIME NUMBER(10, 0) 
, BILLABLE_TIME NUMBER(10, 0) 
, NON_BILL_TIME NUMBER(10, 0) 
, TOTAL_TIME NUMBER(10, 0) 
, BILLABLE_EXP NUMBER 
, NON_BILL_EXP NUMBER 
, TOTAL_EXP NUMBER 
, RESOLUTION VARCHAR2(120 BYTE) 
, X_TRAVEL_TIME NUMBER(10, 1) 
, X_FIXED_TIME DATE 
, X_ACTUAL_START_TIME DATE 
, X_ACTUAL_STOP_TIME DATE 
, X_LABOR_CHARGE NUMBER(19, 4) 
, DATE_MODIFIED DATE 
, X_NON_BILL_OVERTIME NUMBER(10, 0) 
, X_AGREED_DOWNTIME NUMBER(10, 0) 
, NOTES VARCHAR2(4000 BYTE) 
, INTERNAL_NOTES VARCHAR2(765 BYTE) 
, PERF_BY VARCHAR2(90 BYTE) 
, CREATION_TIME_ID NUMBER 
, CONSTRAINT OLD_PK PRIMARY KEY 
  (
    ONSITE_LOG_ID 
  )
  ENABLE 
) 
NOLOGGING 
TABLESPACE "WFMTABLAR" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von TABLE DDL für Objekt DBO.PHONE_LOG_DM nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.PLD_IDX1_CASE_ID ON DBO.PHONE_LOG_DM (CASE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.PLD_IDX2_DATE_ADDED ON DBO.PHONE_LOG_DM (DATE_ADDED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.PLD_IDX3_ACCOUNTABILITY_ID ON DBO.PHONE_LOG_DM (ACCOUNTABILITY_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.PLD_IDX4_EMPLOYEE_ID ON DBO.PHONE_LOG_DM (EMPLOYEE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.PLD_IDX5_CREATE_DATE ON DBO.PHONE_LOG_DM (CREATE_DATE ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.PLD_IDX6_WORK_GROUP ON DBO.PHONE_LOG_DM (WORK_GROUP ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE UNIQUE INDEX DBO.PLD_PK ON DBO.PHONE_LOG_DM (PHONE_LOG_ID ASC, CASE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)CREATE TABLE DBO.PHONE_LOG_DM 
(
  ACCOUNTABILITY_ID VARCHAR2(90 BYTE) 
, CREATE_DATE DATE NOT NULL 
, CASE_ID VARCHAR2(90 BYTE) NOT NULL 
, ACTION_TYPE VARCHAR2(120 BYTE) 
, CASE_SUBCASE VARCHAR2(30 BYTE) 
, EMPLOYEE_ID NUMBER 
, NOTES VARCHAR2(4000 BYTE) 
, WORK_GROUP VARCHAR2(240 BYTE) 
, DATE_ADDED DATE NOT NULL 
, STOP_TIME DATE 
, DURATION NUMBER 
, TIME_TYPE VARCHAR2(120 BYTE) 
, NLS_TIME_TYPE VARCHAR2(240 BYTE) 
, NLS_ACTION_TYPE VARCHAR2(240 BYTE) 
, CONTACT_FIRST_NAME VARCHAR2(90 BYTE) 
, CONTACT_LAST_NAME VARCHAR2(90 BYTE) 
, CONTACT_PHONE VARCHAR2(90 BYTE) 
, COMMITMENT VARCHAR2(240 BYTE) 
, PHONE_LOG_CASE_STATUS VARCHAR2(240 BYTE) 
, PHONE_LOG_ID NUMBER(10, 0) 
, CREATE_DATE_ID NUMBER 
, INTERNAL VARCHAR2(765 BYTE) 
) 
NOLOGGING 
TABLESPACE "WFMTABLAR" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.NLD_PK nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE UNIQUE INDEX DBO.NLD_PK ON DBO.NOTES_LOG_DM (NOTES_LOG_ID, CASE_ID) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.NLD_IDX2_DATE_EMPLOYEE_ID nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.NLD_IDX2_DATE_EMPLOYEE_ID ON DBO.NOTES_LOG_DM (EMPLOYEE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.NLD_IDX3_DATE_ACTION_TYPE nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.NLD_IDX3_DATE_ACTION_TYPE ON DBO.NOTES_LOG_DM (ACTION_TYPE ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.NLD_IDX4_CASE_ID nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.NLD_IDX4_CASE_ID ON DBO.NOTES_LOG_DM (CASE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.NLD_IDX5_ACCOUNTABILITY_ID nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.NLD_IDX5_ACCOUNTABILITY_ID ON DBO.NOTES_LOG_DM (ACCOUNTABILITY_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.NLD_IDX1_DATE_ADDED nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.NLD_IDX1_DATE_ADDED ON DBO.NOTES_LOG_DM (DATE_ADDED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.OLD_IDX1_DATE_MODIFIED nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.OLD_IDX1_DATE_MODIFIED ON DBO.ONSITE_LOG_DM (DATE_MODIFIED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.OLD_IDX2_CASE_ID nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.OLD_IDX2_CASE_ID ON DBO.ONSITE_LOG_DM (CASE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.OLD_IDX4_EMPLOYEE_TABLE_ID nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.OLD_IDX4_EMPLOYEE_TABLE_ID ON DBO.ONSITE_LOG_DM (EMPLOYEE_TABLE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.OLD_IDX3_ACCOUNTABILITY_ID nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.OLD_IDX3_ACCOUNTABILITY_ID ON DBO.ONSITE_LOG_DM (ACCOUNTABILITY_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.OLD_PK nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE UNIQUE INDEX DBO.OLD_PK ON DBO.ONSITE_LOG_DM (ONSITE_LOG_ID) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.PLD_IDX1_CASE_ID nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.PLD_IDX1_CASE_ID ON DBO.PHONE_LOG_DM (CASE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.PLD_IDX2_DATE_ADDED nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.PLD_IDX2_DATE_ADDED ON DBO.PHONE_LOG_DM (DATE_ADDED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.PLD_IDX3_ACCOUNTABILITY_ID nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.PLD_IDX3_ACCOUNTABILITY_ID ON DBO.PHONE_LOG_DM (ACCOUNTABILITY_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.PLD_IDX4_EMPLOYEE_ID nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.PLD_IDX4_EMPLOYEE_ID ON DBO.PHONE_LOG_DM (EMPLOYEE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.PLD_IDX5_CREATE_DATE nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.PLD_IDX5_CREATE_DATE ON DBO.PHONE_LOG_DM (CREATE_DATE ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.PLD_IDX6_WORK_GROUP nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.PLD_IDX6_WORK_GROUP ON DBO.PHONE_LOG_DM (WORK_GROUP ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.PLD_PK nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE UNIQUE INDEX DBO.PLD_PK ON DBO.PHONE_LOG_DM (PHONE_LOG_ID ASC, CASE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
