--------------------------------------------------------
--  Datei erstellt -Dienstag-Juli-19-2011   
--------------------------------------------------------
-- Wiedergabe von TABLE DDL für Objekt DBO.SUBCASE_END2END nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.SE2E_IDX1_DATE_ADDED ON DBO.SUBCASE_END2END (DATE_ADDED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.SE2E_IDX2_DATE_MODIFIED ON DBO.SUBCASE_END2END (DATE_MODIFIED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.SE2E_IDX3_IR_WORK_GROUP ON DBO.SUBCASE_END2END (IR_WORK_GROUP ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)CREATE TABLE DBO.SUBCASE_END2END 
(
  SUBCASE_ID VARCHAR2(90 BYTE) NOT NULL 
, ACCOUNTABILITY_ID VARCHAR2(90 BYTE) 
, SUBCASE_TRACKING_ID VARCHAR2(90 BYTE) NOT NULL 
, SUBCASE_TYPE VARCHAR2(240 BYTE) 
, ACTION_TYPE VARCHAR2(90 BYTE) 
, SUBCASE_TITLE VARCHAR2(240 BYTE) 
, CURRENT_PRIORITY VARCHAR2(240 BYTE) 
, CURRENT_SEVERITY VARCHAR2(240 BYTE) 
, CURRENT_STATUS VARCHAR2(240 BYTE) 
, CONDITION_CODE_VALUE VARCHAR2(240 BYTE) 
, COMMIT_DATE_GMT DATE 
, NB_REOPEN NUMBER 
, NUMBER_ENGINEERS NUMBER 
, NUMBER_OWNERS NUMBER 
, OIE_TYPE VARCHAR2(60 BYTE) 
, OIE_ID VARCHAR2(60 BYTE) 
, CR_DATE_GMT DATE 
, CR_LOGIN_NAME VARCHAR2(120 BYTE) 
, CR_WORK_GROUP VARCHAR2(240 BYTE) 
, CR_EMPLOYEE_FIRST_NAME VARCHAR2(90 BYTE) 
, CR_EMPLOYEE_LAST_NAME VARCHAR2(120 BYTE) 
, CR_RESPONSE_CENTER VARCHAR2(120 BYTE) 
, CR_COUNTRY VARCHAR2(120 BYTE) 
, CR_TIME_ZONE_ID NUMBER 
, FIRST_STATUS_CHANGE VARCHAR2(240 BYTE) 
, TIME_TO_FIRST_RESP_MINS NUMBER 
, IR_DATE_GMT DATE 
, IR_LOGIN_NAME VARCHAR2(120 BYTE) 
, IR_WORK_GROUP VARCHAR2(240 BYTE) 
, IR_EMPLOYEE_FIRST_NAME VARCHAR2(90 BYTE) 
, IR_EMPLOYEE_LAST_NAME VARCHAR2(120 BYTE) 
, IR_RESPONSE_CENTER VARCHAR2(120 BYTE) 
, IR_COUNTRY VARCHAR2(120 BYTE) 
, IR_TIME_ZONE_ID NUMBER 
, LA_ATD VARCHAR2(240 BYTE) 
, LA_DATE_GMT DATE 
, LA_LOGIN_NAME VARCHAR2(120 BYTE) 
, LA_WORK_GROUP VARCHAR2(240 BYTE) 
, LA_EMPLOYEE_FIRST_NAME VARCHAR2(90 BYTE) 
, LA_EMPLOYEE_LAST_NAME VARCHAR2(120 BYTE) 
, LA_RESPONSE_CENTER VARCHAR2(120 BYTE) 
, LA_COUNTRY VARCHAR2(120 BYTE) 
, LA_TIME_ZONE_ID NUMBER 
, OW_LOGIN_NAME VARCHAR2(120 BYTE) 
, OW_WORK_GROUP VARCHAR2(240 BYTE) 
, OW_EMPLOYEE_FIRST_NAME VARCHAR2(90 BYTE) 
, OW_EMPLOYEE_LAST_NAME VARCHAR2(120 BYTE) 
, OW_RESPONSE_CENTER VARCHAR2(120 BYTE) 
, OW_COUNTRY VARCHAR2(120 BYTE) 
, OW_TIME_ZONE_ID NUMBER 
, CL_DATE_GMT DATE 
, CL_LOGIN_NAME VARCHAR2(120 BYTE) 
, CL_WORK_GROUP VARCHAR2(240 BYTE) 
, CL_EMPLOYEE_FIRST_NAME VARCHAR2(90 BYTE) 
, CL_EMPLOYEE_LAST_NAME VARCHAR2(120 BYTE) 
, CL_RESPONSE_CENTER VARCHAR2(120 BYTE) 
, CL_COUNTRY VARCHAR2(120 BYTE) 
, CL_TIME_ZONE_ID NUMBER 
, SUMMARY_TEXT VARCHAR2(765 BYTE) 
, RESOLUTION VARCHAR2(240 BYTE) 
, TIME_IN_OPEN_MINS NUMBER 
, ELAPSED_TIME_MINS NUMBER 
, TIME_IN_MONITOR_MINS NUMBER 
, TTL_TIME_INVEST_BILL_MINS NUMBER 
, TTL_TIME_INVEST_NON_BILL_MINS NUMBER 
, TTL_TIME_INVEST_PHONE_MINS NUMBER 
, TTL_TIME_INVEST_RESEARCH_MINS NUMBER 
, NLS_SUBCASE_ACTION_TYPE VARCHAR2(240 BYTE) 
, NLS_PRIORIY VARCHAR2(240 BYTE) 
, NLS_SEVERITY VARCHAR2(240 BYTE) 
, NLS_RESOLUTION VARCHAR2(240 BYTE) 
, DATE_MODIFIED DATE 
, EMPLOYEE_OWNER NUMBER 
, EMPLOYEE_ORIGINATOR NUMBER 
, EMPLOYEE_CLOSER NUMBER 
, DATE_ADDED DATE 
, X_DELAY_CD NUMBER(10, 0) 
, X_TRAVEL_TIME_MINS NUMBER(10, 0) 
, PARTNER_ID VARCHAR2(24 BYTE) 
, PARTNER_CO_NAME VARCHAR2(240 BYTE) 
, OBLIGATED_LOG_TO_START NUMBER(10, 0) 
, OBLIGATED_LOG_TO_CLOSE NUMBER(10, 0) 
, TOTAL_INVESTED_TIME_MINS NUMBER 
, WDB_DISTRICT VARCHAR2(6 BYTE) 
, WDB_PRODUCT_LINE VARCHAR2(6 BYTE) 
, WDB_WORK_FORCE VARCHAR2(6 BYTE) 
, WDB_OFFICE VARCHAR2(12 BYTE) 
, DELIVERY_ALTERNATIVE VARCHAR2(120 BYTE) 
, ONSITE_FIXED_DATE DATE 
, CONSTRAINT SE2E_PK PRIMARY KEY 
  (
    SUBCASE_ID 
  )
  ENABLE 
) 
NOLOGGING 
TABLESPACE "WFMTABLAR" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.SE2E_IDX1_DATE_ADDED nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.SE2E_IDX1_DATE_ADDED ON DBO.SUBCASE_END2END (DATE_ADDED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.SE2E_IDX2_DATE_MODIFIED nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.SE2E_IDX2_DATE_MODIFIED ON DBO.SUBCASE_END2END (DATE_MODIFIED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.SE2E_IDX3_IR_WORK_GROUP nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.SE2E_IDX3_IR_WORK_GROUP ON DBO.SUBCASE_END2END (IR_WORK_GROUP ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.SE2E_PK nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE UNIQUE INDEX DBO.SE2E_PK ON DBO.SUBCASE_END2END (SUBCASE_ID) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
