--------------------------------------------------------
--  Datei erstellt -Dienstag-Juli-19-2011   
--------------------------------------------------------
-- Wiedergabe von TABLE DDL für Objekt DBO.CASE_END2END nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.CE2E_IDX1_DATE_ADDED ON DBO.CASE_END2END (DATE_ADDED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.CE2E_IDX2_DATE_MODIFIED ON DBO.CASE_END2END (DATE_MODIFIED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.CE2E_IDX2_X_HP_ID ON DBO.CASE_END2END (X_HP_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.CE2E_IDX3_NAME ON DBO.CASE_END2END (NAME ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.CE2E_IDX4_SYSTEM_HANDLE ON DBO.CASE_END2END (SYSTEM_HANDLE ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.CE2E_IDX5_IR_WORK_GROUP ON DBO.CASE_END2END (IR_WORK_GROUP ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.CE2E_IDX6_X_SERVICE_ID ON DBO.CASE_END2END (X_SERVICE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.IMTEAM_CASE_END2END_IDX_1 ON DBO.CASE_END2END (CR_DATE_GMT ASC) 
LOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.IMTEAM_CASE_END2END_IDX_2 ON DBO.CASE_END2END (CL_DATE_GMT ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)CREATE TABLE DBO.CASE_END2END 
(
  CASE_ID VARCHAR2(90 BYTE) NOT NULL 
, ACCOUNTABILITY_ID VARCHAR2(90 BYTE) NOT NULL 
, CALL_TYPE VARCHAR2(240 BYTE) 
, CASE_TITLE VARCHAR2(240 BYTE) 
, ADDNL_INFO_INITIAL_PRIORITY VARCHAR2(765 BYTE) 
, CURRENT_PRIORITY VARCHAR2(240 BYTE) 
, ADDNL_INFO_INITIAL_SEVERITY VARCHAR2(765 BYTE) 
, CURRENT_SEVERITY VARCHAR2(240 BYTE) 
, CURRENT_STATUS VARCHAR2(240 BYTE) 
, CONDITION_CODE_VALUE VARCHAR2(90 BYTE) 
, NB_REOPEN NUMBER 
, NUMBER_ENGINEERS NUMBER 
, NUMBER_OWNERS NUMBER 
, CONTRACT_ID VARCHAR2(90 BYTE) 
, SYSTEM_HANDLE VARCHAR2(120 BYTE) 
, NAME VARCHAR2(240 BYTE) 
, ADDRESS VARCHAR2(600 BYTE) 
, ADDRESS2 VARCHAR2(600 BYTE) 
, ZIP_CODE VARCHAR2(90 BYTE) 
, CITY VARCHAR2(120 BYTE) 
, COUNTRY VARCHAR2(120 BYTE) 
, MAID VARCHAR2(90 BYTE) 
, SEGMENT VARCHAR2(120 BYTE) 
, CREDIT_CARD VARCHAR2(6 BYTE) 
, CREDIT_CARD_BILL_TYPE VARCHAR2(60 BYTE) 
, CONTACT_FIRST_NAME VARCHAR2(90 BYTE) 
, CONTACT_LAST_NAME VARCHAR2(90 BYTE) 
, CALLER_PHONE VARCHAR2(90 BYTE) 
, CONTACT_E_MAIL VARCHAR2(240 BYTE) 
, DOMAIN VARCHAR2(90 BYTE) 
, PRODUCT_FAMILY VARCHAR2(120 BYTE) 
, ROUTING VARCHAR2(120 BYTE) 
, PLATFORM VARCHAR2(90 BYTE) 
, PRODUCT VARCHAR2(90 BYTE) 
, PRODUCT_DESCRIPTION VARCHAR2(765 BYTE) 
, CASE_CATEGORY VARCHAR2(6 BYTE) 
, PRODUCT_LINE VARCHAR2(90 BYTE) 
, SERIAL_NUMBER VARCHAR2(90 BYTE) 
, SERVICE_NOTE_NUMBER VARCHAR2(60 BYTE) 
, WARR_PROOF_PURCHASE DATE 
, WARR_CODE VARCHAR2(6 BYTE) 
, WARR_DESC VARCHAR2(240 BYTE) 
, WARR_RESP VARCHAR2(30 BYTE) 
, CUSTOMER_TRACKING_NBR VARCHAR2(60 BYTE) 
, CR_DATE_GMT DATE 
, CR_DATE_CUST DATE 
, CR_LOGIN_NAME VARCHAR2(120 BYTE) 
, CR_WORK_GROUP VARCHAR2(240 BYTE) 
, CR_EMPLOYEE_FIRST_NAME VARCHAR2(90 BYTE) 
, CR_EMPLOYEE_LAST_NAME VARCHAR2(120 BYTE) 
, CR_RESPONSE_CENTER VARCHAR2(120 BYTE) 
, CR_COUNTRY VARCHAR2(120 BYTE) 
, CR_TIME_ZONE_ID NUMBER 
, IR_FIRST_STATUS_CHANGE VARCHAR2(120 BYTE) 
, TIME_TO_FIRST_RESPONSE_MINS NUMBER 
, RESPONSE_TIME_CONTRACTUAL_MINS NUMBER 
, IR_DATE_GMT DATE 
, IR_DATE_CUST DATE 
, IR_LOGIN_NAME VARCHAR2(120 BYTE) 
, IR_WORK_GROUP VARCHAR2(240 BYTE) 
, IR_EMPLOYEE_FIRST_NAME VARCHAR2(90 BYTE) 
, IR_EMPLOYEE_LAST_NAME VARCHAR2(120 BYTE) 
, IR_RESPONSE_CENTER VARCHAR2(120 BYTE) 
, IR_COUNTRY VARCHAR2(120 BYTE) 
, IR_TIME_ZONE_ID NUMBER 
, LA_ATD VARCHAR2(240 BYTE) 
, LA_DATE_GMT DATE 
, LA_DATE_CUST DATE 
, LA_LOGIN_NAME VARCHAR2(120 BYTE) 
, LA_WORK_GROUP VARCHAR2(240 BYTE) 
, LA_EMPLOYEE_FIRST_NAME VARCHAR2(90 BYTE) 
, LA_EMPLOYEE_LAST_NAME VARCHAR2(120 BYTE) 
, LA_RESPONSE_CENTER VARCHAR2(120 BYTE) 
, LA_COUNTRY VARCHAR2(120 BYTE) 
, LA_TIME_ZONE_ID NUMBER 
, OW_LOGIN_NAME VARCHAR2(120 BYTE) 
, OW_WORK_GROUP VARCHAR2(240 BYTE) 
, OW_EMPLOYEE_FIRST_NAME VARCHAR2(90 BYTE) 
, OW_EMPLOYEE_LAST_NAME VARCHAR2(120 BYTE) 
, OW_RESPONSE_CENTER VARCHAR2(120 BYTE) 
, OW_COUNTRY VARCHAR2(120 BYTE) 
, OW_TIME_ZONE_ID NUMBER 
, CL_DATE_GMT DATE 
, CL_DATE_CUST DATE 
, CL_LOGIN_NAME VARCHAR2(120 BYTE) 
, CL_WORK_GROUP VARCHAR2(240 BYTE) 
, CL_EMPLOYEE_FIRST_NAME VARCHAR2(90 BYTE) 
, CL_EMPLOYEE_LAST_NAME VARCHAR2(120 BYTE) 
, CL_RESPONSE_CENTER VARCHAR2(120 BYTE) 
, CL_COUNTRY VARCHAR2(120 BYTE) 
, CL_TIME_ZONE_ID NUMBER 
, SUMMARY_TEXT VARCHAR2(765 BYTE) 
, RESOLUTION VARCHAR2(240 BYTE) 
, WARRANTY_STATUS VARCHAR2(45 BYTE) 
, TIME_IN_OPEN_MINS NUMBER 
, ELAPSED_TIME_MINS NUMBER 
, TIME_IN_MONITOR_MINS NUMBER 
, TTL_TIME_INVEST_BILL_MINS NUMBER 
, TTL_TIME_INVEST_NON_BILL_MINS NUMBER 
, TTL_TIME_INVEST_PHONE_MINS NUMBER 
, TTL_TIME_INVEST_RESEARCH_MINS NUMBER 
, X_ESCALATION_LEVEL VARCHAR2(90 BYTE) 
, X_ESCALATION_MANAGEMENT VARCHAR2(90 BYTE) 
, TIME_TO_SOLVE_IN_ESCALATION NUMBER 
, ACCESSORY_X_NAME VARCHAR2(210 BYTE) 
, OSNOS_X_NAME VARCHAR2(120 BYTE) 
, X_IP_MODEL VARCHAR2(120 BYTE) 
, DIAGNOSTIC_IP_ID NUMBER 
, DIAGTOOL_IP_ID NUMBER 
, QUALITY_IP_ID NUMBER 
, NLS_LANGUAGE VARCHAR2(18 BYTE) 
, NLS_CALL_TYPE VARCHAR2(240 BYTE) 
, NLS_PRIORITY VARCHAR2(240 BYTE) 
, NLS_SEVERITY VARCHAR2(240 BYTE) 
, NLS_STATUS VARCHAR2(240 BYTE) 
, NLS_RESOLUTION VARCHAR2(240 BYTE) 
, DATE_MODIFIED DATE 
, EMPLOYEE_OWNER NUMBER 
, EMPLOYEE_ORIGINATOR NUMBER 
, EMPLOYEE_CLOSER NUMBER 
, DATE_ADDED DATE 
, X_TRAVEL_TIME_MINS NUMBER(10, 0) 
, HW_CASE_ELAPSED_START_TO_CLOSE NUMBER(10, 0) 
, CONTINUE_EFFORT_FLAG NUMBER(1, 0) 
, OBLIGATED_LOG_TO_START NUMBER(10, 0) 
, OBLIGATED_LOG_TO_CLOSE NUMBER(10, 0) 
, OBLIGATED_START_TO_CLOSE NUMBER(10, 0) 
, TOTAL_INVESTED_TIME_MINS NUMBER 
, WDB_DISTRICT VARCHAR2(6 BYTE) 
, WDB_PRODUCT_LINE VARCHAR2(6 BYTE) 
, WDB_WORK_FORCE VARCHAR2(6 BYTE) 
, WDB_OFFICE VARCHAR2(12 BYTE) 
, GEO_ISO_COUNTRY_CD VARCHAR2(6 BYTE) 
, GEO_ISO_COUNTRY_NAME VARCHAR2(120 BYTE) 
, GEO_ISO_SHIP_COUNTRY_CD VARCHAR2(6 BYTE) 
, GEO_ISO_SHIP_COUNTRY_NAME VARCHAR2(120 BYTE) 
, ENTRY_POINT VARCHAR2(120 BYTE) 
, RESPONSE_MISSED NUMBER(1, 0) 
, DELIVERY_ALTERNATIVE VARCHAR2(120 BYTE) 
, CTR_FLAG NUMBER(1, 0) 
, ONSITE_FIXED_DATE DATE 
, QUAL_START_DATE DATE 
, QUAL_EMPLOYEE_TABLE_ID NUMBER(10, 0) 
, X_HP_ID VARCHAR2(180 BYTE) 
, X_TYPE_CD NUMBER(4, 0) 
, ENTITLEMENT_X_HP_ID VARCHAR2(180 BYTE) 
, ENTITLEMENT_X_TYPE_CD NUMBER(4, 0) 
, SERVICE_X_HP_ID VARCHAR2(180 BYTE) 
, SERVICE_X_TYPE_CD NUMBER(4, 0) 
, SEARCHED_X_HP_ID VARCHAR2(180 BYTE) 
, SEARCHED_X_TYPE_CD NUMBER(4, 0) 
, X_SERVICE_ID VARCHAR2(90 BYTE) 
, STATE_PRVNC_NAME VARCHAR2(120 BYTE) 
, M8_QUALIFIED NUMBER(1, 0) 
, CUSTOMER_RESCHEDULED_MISSED NUMBER(1, 0) 
, M1_HW_COUNT NUMBER(1, 0) 
, M1A_HW_COUNT NUMBER(1, 0) 
, M1B_HW_COUNT NUMBER(1, 0) 
, M2_HW_RPR_COUNT NUMBER(1, 0) 
, PIN VARCHAR2(60 BYTE) 
, HP_AUTH_EMPLOYEE_ID NUMBER 
, CONSTRAINT CE2E_PK PRIMARY KEY 
  (
    CASE_ID 
  )
  ENABLE 
) 
NOLOGGING 
TABLESPACE "WFMTABLAR" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.CE2E_IDX2_X_HP_ID nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.CE2E_IDX2_X_HP_ID ON DBO.CASE_END2END (X_HP_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.CE2E_IDX6_X_SERVICE_ID nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.CE2E_IDX6_X_SERVICE_ID ON DBO.CASE_END2END (X_SERVICE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.CE2E_IDX1_DATE_ADDED nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.CE2E_IDX1_DATE_ADDED ON DBO.CASE_END2END (DATE_ADDED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.CE2E_IDX2_DATE_MODIFIED nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.CE2E_IDX2_DATE_MODIFIED ON DBO.CASE_END2END (DATE_MODIFIED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.CE2E_IDX3_NAME nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.CE2E_IDX3_NAME ON DBO.CASE_END2END (NAME ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.CE2E_IDX4_SYSTEM_HANDLE nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.CE2E_IDX4_SYSTEM_HANDLE ON DBO.CASE_END2END (SYSTEM_HANDLE ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.CE2E_IDX5_IR_WORK_GROUP nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.CE2E_IDX5_IR_WORK_GROUP ON DBO.CASE_END2END (IR_WORK_GROUP ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.CE2E_PK nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE UNIQUE INDEX DBO.CE2E_PK ON DBO.CASE_END2END (CASE_ID) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.IMTEAM_CASE_END2END_IDX_1 nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.IMTEAM_CASE_END2END_IDX_1 ON DBO.CASE_END2END (CR_DATE_GMT ASC) 
LOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.IMTEAM_CASE_END2END_IDX_2 nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.IMTEAM_CASE_END2END_IDX_2 ON DBO.CASE_END2END (CL_DATE_GMT ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
