--------------------------------------------------------
--  Datei erstellt -Dienstag-Juli-19-2011   
--------------------------------------------------------
-- Wiedergabe von TABLE DDL für Objekt DBO.EMPLOYEE_TABLE_DM nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.ETD_IDX1_DATE_ADDED ON DBO.EMPLOYEE_TABLE_DM (DATE_ADDED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXMED" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 4194304 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.ETD_IDX2_DATE_MODIFIED ON DBO.EMPLOYEE_TABLE_DM (DATE_MODIFIED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXMED" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 4194304 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.ETD_IDX3_TIME_ZONE_ID ON DBO.EMPLOYEE_TABLE_DM (TIME_ZONE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXMED" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 4194304 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)CREATE TABLE DBO.EMPLOYEE_TABLE_DM 
(
  EMPLOYEE_TABLE_ID NUMBER NOT NULL 
, CORE_PROCESS_DESC VARCHAR2(24 BYTE) 
, COUNTRY VARCHAR2(120 BYTE) 
, EMPLOYEE_FIRST_NAME VARCHAR2(90 BYTE) 
, EMPLOYEE_ID VARCHAR2(30 BYTE) 
, EMPLOYEE_LAST_NAME VARCHAR2(120 BYTE) 
, EMPLOYEE_SITE VARCHAR2(120 BYTE) 
, EMPLOYEE_SITE_ID VARCHAR2(240 BYTE) 
, EMPLOYEE_SUPVR_ID NUMBER 
, LOCATION VARCHAR2(240 BYTE) 
, LOGIN_NAME VARCHAR2(120 BYTE) 
, REGION VARCHAR2(90 BYTE) 
, RESPONSE_CENTER VARCHAR2(120 BYTE) 
, ORGANIZATION VARCHAR2(24 BYTE) 
, TIME_ZONE_ID NUMBER NOT NULL 
, WORK_GROUP VARCHAR2(240 BYTE) 
, DATE_ADDED DATE 
, DATE_MODIFIED DATE 
, EMPLOYEE_PHONE VARCHAR2(75 BYTE) 
, BLUE_RED_CD VARCHAR2(6 BYTE) 
, PAGER_PHONE VARCHAR2(75 BYTE) 
, PAGER_PIN VARCHAR2(75 BYTE) 
, ASSIGN_BADGE_NUM VARCHAR2(24 BYTE) 
, ACTIVE_FLAG VARCHAR2(3 BYTE) 
, ACTING_SUPVR_FLAG NUMBER(1, 0) 
, EMPLOYEE_TYPE VARCHAR2(3 BYTE) 
, WDB_OFFICE VARCHAR2(12 BYTE) 
, WDB_SCS VARCHAR2(66 BYTE) 
, USER_TABLE_ID NUMBER(10, 0) 
, RC_CONFIG_NAME VARCHAR2(240 BYTE) 
, PRIV_ACCESS_CLASS_NAME VARCHAR2(240 BYTE) 
, PRIV_OFFLINE_CLASS_NAME VARCHAR2(240 BYTE) 
, EMPLOYEE_EMAIL VARCHAR2(240 BYTE) 
, X_CE_APPLICATION VARCHAR2(60 BYTE) 
, CONSTRAINT ETD_PK PRIMARY KEY 
  (
    EMPLOYEE_TABLE_ID 
  )
  ENABLE 
) 
NOLOGGING 
TABLESPACE "WFMTABLAR" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.ETD_IDX1_DATE_ADDED nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.ETD_IDX1_DATE_ADDED ON DBO.EMPLOYEE_TABLE_DM (DATE_ADDED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXMED" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 4194304 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.ETD_IDX2_DATE_MODIFIED nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.ETD_IDX2_DATE_MODIFIED ON DBO.EMPLOYEE_TABLE_DM (DATE_MODIFIED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXMED" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 4194304 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.ETD_IDX3_TIME_ZONE_ID nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.ETD_IDX3_TIME_ZONE_ID ON DBO.EMPLOYEE_TABLE_DM (TIME_ZONE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXMED" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 4194304 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.ETD_PK nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE UNIQUE INDEX DBO.ETD_PK ON DBO.EMPLOYEE_TABLE_DM (EMPLOYEE_TABLE_ID) 
NOLOGGING 
TABLESPACE "WFMIDXMED" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 4194304 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
