--------------------------------------------------------
--  Datei erstellt -Dienstag-Juli-19-2011   
--------------------------------------------------------
-- Wiedergabe von TABLE DDL für Objekt DBO.HP_COUNTRY_DM nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE TABLE DBO.HP_COUNTRY_DM 
(
  COUNTRY_ID NUMBER(10, 0) NOT NULL 
, COUNTRY_CODE NUMBER(10, 0) 
, DEV NUMBER(10, 0) 
, CURRENCY_ID NUMBER(10, 0) 
, X_ISO_CODE VARCHAR2(6 BYTE) 
, X_CHARACTER_SET VARCHAR2(120 BYTE) 
, X_SUPER_REGION VARCHAR2(12 BYTE) 
, NAME VARCHAR2(120 BYTE) 
, CONSTRAINT HCD_PK PRIMARY KEY 
  (
    COUNTRY_ID 
  )
  ENABLE 
) 
NOLOGGING 
TABLESPACE "WFMTABMED" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 4194304 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.HCD_PK nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE UNIQUE INDEX DBO.HCD_PK ON DBO.HP_COUNTRY_DM (COUNTRY_ID) 
NOLOGGING 
TABLESPACE "WFMIDXMED" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 4194304 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
