--------------------------------------------------------
--  Datei erstellt -Dienstag-Juli-19-2011   
--------------------------------------------------------
-- Wiedergabe von TABLE DDL für Objekt DBO.HP_PARTS_INFO_DM nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.HPID_IDX1_DATE_ADDED ON DBO.HP_PARTS_INFO_DM (DATE_ADDED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXMED" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 4194304 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.HPID_IDX2_DATE_MODIFIED ON DBO.HP_PARTS_INFO_DM (DATE_MODIFIED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXMED" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 4194304 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.HPID_IDX3_PART_ORDER_ID ON DBO.HP_PARTS_INFO_DM (HP_PART_ORDER_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.HPID_IDX3_X_PART_USAGE ON DBO.HP_PARTS_INFO_DM (X_PART_USAGE ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)CREATE TABLE DBO.HP_PARTS_INFO_DM 
(
  ACCOUNTABILITY_ID VARCHAR2(90 BYTE) NOT NULL 
, SUBCASE_TRACKING_ID VARCHAR2(90 BYTE) NOT NULL 
, PARTS_INFO_ID NUMBER NOT NULL 
, ORDER_NUMBER VARCHAR2(48 BYTE) 
, CLFY_USER_LOGIN VARCHAR2(60 BYTE) 
, EXTERNAL_USER_LOGIN VARCHAR2(60 BYTE) 
, SELECTED_QUANTITY NUMBER 
, PART_NUMBER VARCHAR2(120 BYTE) 
, PART_DESC VARCHAR2(480 BYTE) 
, PART_CLASS_DESC VARCHAR2(30 BYTE) 
, CURRENCY VARCHAR2(30 BYTE) 
, LIST_PRICE NUMBER 
, SOURCE_LOCATION VARCHAR2(120 BYTE) 
, TIMESTAMP DATE 
, TYPE_FLAG VARCHAR2(6 BYTE) 
, DATE_ADDED DATE NOT NULL 
, DATE_MODIFIED DATE NOT NULL 
, PART_MODIFIER_CD VARCHAR2(90 BYTE) 
, PART_MODIFIER_DESC VARCHAR2(765 BYTE) 
, CALLPACK_PART_NUM VARCHAR2(90 BYTE) 
, CALLPACK_PART_DESC VARCHAR2(765 BYTE) 
, PART_EST_ARRV_TIME DATE 
, X_FAILURE_CD VARCHAR2(12 BYTE) 
, X_SERIAL_NUMBER VARCHAR2(90 BYTE) 
, X_REMOVED_SERIAL_NUMBER VARCHAR2(90 BYTE) 
, X_PRODUCT_LINE VARCHAR2(12 BYTE) 
, X_SHIP_DATE DATE 
, X_RMA_NUMBER VARCHAR2(48 BYTE) 
, X_PART_STATUS VARCHAR2(60 BYTE) 
, X_LINE_NUMBER NUMBER(10, 0) 
, X_PART_NOTES VARCHAR2(240 BYTE) 
, X_WAYBILL VARCHAR2(120 BYTE) 
, X_CARRIER_ID VARCHAR2(120 BYTE) 
, X_PART_TYPE VARCHAR2(60 BYTE) 
, X_BOM_FLAG NUMBER(1, 0) 
, X_ESCALATED_FLAG NUMBER(1, 0) 
, X_BILLABLE NUMBER(10, 0) 
, X_OFFER_PART_NUMBER VARCHAR2(120 BYTE) 
, X_PART_USAGE VARCHAR2(54 BYTE) 
, X_SC_ETA DATE 
, X_REMOVED_PART_DESC VARCHAR2(480 BYTE) 
, X_REMOVED_PART_NUMBER VARCHAR2(120 BYTE) 
, X_RETURN_DEADLINE DATE 
, X_RETURN_INSTRUCTIONS VARCHAR2(765 BYTE) 
, X_RETURN_OVERRIDE_FLAG NUMBER(1, 0) 
, X_TRACKING_NUMBER VARCHAR2(120 BYTE) 
, X_UNIT_SWAP_FLAG NUMBER(1, 0) 
, X_SVC_PRODUCT_LINE VARCHAR2(18 BYTE) 
, X_CANCEL_FLAG NUMBER(1, 0) 
, X_FUNC_EQ_FLAG NUMBER(1, 0) 
, X_FUNC_EQ_PART_NUMBER VARCHAR2(120 BYTE) 
, X_LAST_MOD_TIME DATE 
, X_LOGISTICS_LINE_NUMBER NUMBER(10, 0) 
, X_RECONCILIATION_RESULT VARCHAR2(60 BYTE) 
, X_RESERVED_FLAG NUMBER(1, 0) 
, X_CREATION_TIME DATE 
, X_FAILURE_ANALYSIS_FLAG NUMBER(1, 0) 
, CASE_ID VARCHAR2(90 BYTE) 
, X_REPAIR_TYPE VARCHAR2(60 BYTE) 
, X_PART_QUALIFICATION2USER NUMBER(10, 0) 
, HP_PART_ORDER_ID NUMBER(10, 0) 
, X_PART_SOURCED2USER NUMBER(10, 0) 
, X_PICK_PACK_INSTRUCTIONS VARCHAR2(765 BYTE) 
, X_DLVR_PRIOR_CD VARCHAR2(12 BYTE) 
, X_SHIP_METHOD_CD VARCHAR2(12 BYTE) 
, X_SHIP_INST_CD VARCHAR2(12 BYTE) 
, X_SPECIAL_INST_CD VARCHAR2(12 BYTE) 
, X_ORDERED_DT DATE 
, X_REQD_PART_NUMBER VARCHAR2(120 BYTE) 
, X_RETURNABLE_CD VARCHAR2(3 BYTE) 
, X_NLS_PART_STATUS VARCHAR2(120 BYTE) 
, X_NLS_PART_USAGE VARCHAR2(120 BYTE) 
, X_CUSTOMER_RECEIVED_DATE DATE 
, X_CRITICAL_FOR_REPAIR_FLAG NUMBER 
, CONSTRAINT HPID_PK PRIMARY KEY 
  (
    ACCOUNTABILITY_ID 
  , PARTS_INFO_ID 
  , SUBCASE_TRACKING_ID 
  )
  ENABLE 
) 
NOLOGGING 
TABLESPACE "WFMTABMED" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 4194304 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.HPID_IDX3_PART_ORDER_ID nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.HPID_IDX3_PART_ORDER_ID ON DBO.HP_PARTS_INFO_DM (HP_PART_ORDER_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.HPID_IDX3_X_PART_USAGE nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.HPID_IDX3_X_PART_USAGE ON DBO.HP_PARTS_INFO_DM (X_PART_USAGE ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.HPID_IDX1_DATE_ADDED nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.HPID_IDX1_DATE_ADDED ON DBO.HP_PARTS_INFO_DM (DATE_ADDED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXMED" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 4194304 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.HPID_IDX2_DATE_MODIFIED nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.HPID_IDX2_DATE_MODIFIED ON DBO.HP_PARTS_INFO_DM (DATE_MODIFIED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXMED" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 4194304 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.HPID_PK nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE UNIQUE INDEX DBO.HPID_PK ON DBO.HP_PARTS_INFO_DM (ACCOUNTABILITY_ID, PARTS_INFO_ID, SUBCASE_TRACKING_ID) 
NOLOGGING 
TABLESPACE "WFMIDXMED" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 4194304 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
