--------------------------------------------------------
--  Datei erstellt -Dienstag-Juli-19-2011   
--------------------------------------------------------
-- Wiedergabe von TABLE DDL für Objekt DBO.WFM_SUBCASE nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.IMTEAM_WFM_SUBCASE_IDX_2 ON DBO.WFM_SUBCASE (OPEN_DATE ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.WC_IDX12_X_REPAIR_CLASS ON DBO.WFM_SUBCASE (X_REPAIR_CLASS ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.WS_IDX10_OPEN_DATE_ID ON DBO.WFM_SUBCASE (OPEN_DATE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.WS_IDX11_EMPLOYEE_CLOSER ON DBO.WFM_SUBCASE (EMPLOYEE_CLOSER ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.WS_IDX13_X_SERIAL_NO ON DBO.WFM_SUBCASE (X_SERIAL_NO ASC) 
LOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.WS_IDX1_DATE_ADDED ON DBO.WFM_SUBCASE (DATE_ADDED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.WS_IDX2_DATE_MODIFIED ON DBO.WFM_SUBCASE (DATE_MODIFIED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.WS_IDX3_SUBCASE_TRACKING_ID ON DBO.WFM_SUBCASE (SUBCASE_TRACKING_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.WS_IDX4_CASE_ACCOUNTABILITY_ID ON DBO.WFM_SUBCASE (CASE_ACCOUNTABILITY_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.WS_IDX5_SUBCASE_TYPE ON DBO.WFM_SUBCASE (SUBCASE_TYPE ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.WS_IDX6_EMPLOYEE_ORIGINATOR ON DBO.WFM_SUBCASE (EMPLOYEE_ORIGINATOR ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.WS_IDX7_EMPLOYEE_OWNER ON DBO.WFM_SUBCASE (EMPLOYEE_OWNER ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.WS_IDX8_CLOSE_DATE_ID ON DBO.WFM_SUBCASE (CLOSE_DATE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX DBO.WS_IDX9_CLOSE_DATE ON DBO.WFM_SUBCASE (CLOSE_DATE ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)CREATE TABLE DBO.WFM_SUBCASE 
(
  SUBCASE_ID VARCHAR2(90 BYTE) NOT NULL 
, SUBCASE_TRACKING_ID VARCHAR2(90 BYTE) NOT NULL 
, CASE_ACCOUNTABILITY_ID VARCHAR2(90 BYTE) 
, SUBCASE_TYPE VARCHAR2(240 BYTE) 
, ACTION_TYPE VARCHAR2(90 BYTE) 
, SUBCASE_TITLE VARCHAR2(240 BYTE) 
, PRIORITY VARCHAR2(240 BYTE) 
, SEVERITY VARCHAR2(240 BYTE) 
, COMMIT_DATE DATE 
, COMMIT_DATE_ID NUMBER 
, STATUS VARCHAR2(240 BYTE) 
, NUMBER_ENGINEERS NUMBER 
, NUMBER_OWNERS NUMBER 
, OPEN_DATE DATE 
, OPEN_DATE_ID NUMBER 
, EMPLOYEE_ORIGINATOR NUMBER 
, RESPONSE_TIME_ACTUAL NUMBER 
, EMPLOYEE_OWNER NUMBER 
, CLOSE_DATE DATE 
, CLOSE_DATE_ID NUMBER 
, EMPLOYEE_CLOSER NUMBER 
, SUMMARY_TEXT VARCHAR2(765 BYTE) 
, RESOLUTION VARCHAR2(240 BYTE) 
, TIME_IN_OPEN NUMBER 
, ELAPSED_TIME NUMBER 
, TIME_IN_MONITOR NUMBER 
, TIME_INVESTED_TE_BILLABLE NUMBER 
, TIME_INVESTED_TE_NON_BILLABLE NUMBER 
, TIME_INVESTED_PHONE NUMBER 
, TIME_INVESTED_RESEARCH NUMBER 
, DATE_ADDED DATE 
, DATE_MODIFIED DATE 
, CONDITION_CODE NUMBER 
, CONDITION_CODE_VALUE VARCHAR2(240 BYTE) 
, NLS_SUBCASE_ACTION_TYPE VARCHAR2(240 BYTE) 
, NLS_PRIORITY VARCHAR2(240 BYTE) 
, NLS_SEVERITY VARCHAR2(240 BYTE) 
, NLS_RESOLUTION VARCHAR2(240 BYTE) 
, OIE_ID VARCHAR2(60 BYTE) 
, OIE_TYPE VARCHAR2(60 BYTE) 
, ACTL_PHONE_TIME NUMBER 
, ACTL_RESEARCH_TIME NUMBER 
, X_REPAIR_CLASS VARCHAR2(6 BYTE) 
, X_SYSTEM_PART_NUMBER VARCHAR2(90 BYTE) 
, X_SYSTEM_SERIAL_NO VARCHAR2(90 BYTE) 
, X_OTC VARCHAR2(60 BYTE) 
, X_DELAY_CD NUMBER(10, 0) 
, X_TRAVEL_TIME NUMBER(10, 0) 
, PARTNER_ID VARCHAR2(24 BYTE) 
, PARTNER_CO_NAME VARCHAR2(240 BYTE) 
, DAYS_OPEN NUMBER(10, 0) 
, OBLIGATED_LOG_TO_START NUMBER(10, 0) 
, OBLIGATED_LOG_TO_CLOSE NUMBER(10, 0) 
, TOTAL_INVESTED_TIME NUMBER 
, WDB_DISTRICT VARCHAR2(6 BYTE) 
, WDB_PRODUCT_LINE VARCHAR2(6 BYTE) 
, WDB_WORK_FORCE VARCHAR2(6 BYTE) 
, WDB_OFFICE VARCHAR2(12 BYTE) 
, DEPOT_NTF_FLAG NUMBER(1, 0) 
, SUBCASE_SVC_CAT VARCHAR2(60 BYTE) 
, PART_QTY_USED NUMBER(5, 0) 
, DELIVERY_ALTERNATIVE VARCHAR2(120 BYTE) 
, NUM_PARTS_RECOMMENDED NUMBER(5, 0) 
, NO_PARTS_RECOMMENDED NUMBER(1, 0) 
, PARTS_RECOMMENDED_NPU NUMBER(1, 0) 
, PARTS_DIAGNOSIS_ACCURACY NUMBER(10, 2) 
, PARTS_DIAGNOSIS_EFFICIENCY NUMBER(10, 2) 
, M9_NPU NUMBER(1, 0) 
, X_FMN_CSO VARCHAR2(96 BYTE) 
, REQUIRED_DATE DATE 
, PREFERRED_ENGINEER_FIRST_NAME VARCHAR2(75 BYTE) 
, PREFERRED_ENGINEER_LAST_NAME VARCHAR2(75 BYTE) 
, BACKUP_ENGINEER_FIRST_NAME VARCHAR2(75 BYTE) 
, BACKUP_ENGINEER_LAST_NAME VARCHAR2(75 BYTE) 
, X_SERVICE_LOCATION VARCHAR2(240 BYTE) 
, X_TRAVEL_ZONE VARCHAR2(6 BYTE) 
, QUALIFIER_EMP_NO VARCHAR2(24 BYTE) 
, PART_STATUS VARCHAR2(240 BYTE) 
, ONSITE_OFFSITE_FL VARCHAR2(6 BYTE) 
, ONSITE_FIXED_DATE DATE 
, ONSITE_START_DATE DATE 
, ONSITE_STOP_DATE DATE 
, OFFSITE_START_DATE DATE 
, OFFSITE_STOP_DATE DATE 
, RM_REVISION_COUNTER NUMBER(10, 0) 
, X_PART_NUMBER VARCHAR2(90 BYTE) 
, X_SERVICE_NOTE_NUMBER VARCHAR2(60 BYTE) 
, SYSTEM_PART_DESCRIPTION VARCHAR2(765 BYTE) 
, CURRENT_QUEUE_ID NUMBER(10, 0) 
, X_SERIAL_NO VARCHAR2(90 BYTE) 
, PSP_ID VARCHAR2(45 BYTE) 
, CE_STATUS VARCHAR2(240 BYTE) 
, VOID_RESOLUTION_FLAG NUMBER(1, 0) 
, PREVIOUS_EMPLOYEE_OWNER NUMBER 
, CONSTRAINT WS_PK PRIMARY KEY 
  (
    SUBCASE_ID 
  )
  ENABLE 
) 
NOLOGGING 
TABLESPACE "WFMTABLAR" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.WS_IDX10_OPEN_DATE_ID nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.WS_IDX10_OPEN_DATE_ID ON DBO.WFM_SUBCASE (OPEN_DATE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.WS_IDX3_SUBCASE_TRACKING_ID nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.WS_IDX3_SUBCASE_TRACKING_ID ON DBO.WFM_SUBCASE (SUBCASE_TRACKING_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.WS_IDX13_X_SERIAL_NO nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.WS_IDX13_X_SERIAL_NO ON DBO.WFM_SUBCASE (X_SERIAL_NO ASC) 
LOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.IMTEAM_WFM_SUBCASE_IDX_2 nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.IMTEAM_WFM_SUBCASE_IDX_2 ON DBO.WFM_SUBCASE (OPEN_DATE ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.WS_IDX1_DATE_ADDED nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.WS_IDX1_DATE_ADDED ON DBO.WFM_SUBCASE (DATE_ADDED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.WS_IDX2_DATE_MODIFIED nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.WS_IDX2_DATE_MODIFIED ON DBO.WFM_SUBCASE (DATE_MODIFIED ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.WS_IDX4_CASE_ACCOUNTABILITY_ID nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.WS_IDX4_CASE_ACCOUNTABILITY_ID ON DBO.WFM_SUBCASE (CASE_ACCOUNTABILITY_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.WS_IDX5_SUBCASE_TYPE nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.WS_IDX5_SUBCASE_TYPE ON DBO.WFM_SUBCASE (SUBCASE_TYPE ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.WS_IDX6_EMPLOYEE_ORIGINATOR nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.WS_IDX6_EMPLOYEE_ORIGINATOR ON DBO.WFM_SUBCASE (EMPLOYEE_ORIGINATOR ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.WS_IDX7_EMPLOYEE_OWNER nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.WS_IDX7_EMPLOYEE_OWNER ON DBO.WFM_SUBCASE (EMPLOYEE_OWNER ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.WS_IDX8_CLOSE_DATE_ID nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.WS_IDX8_CLOSE_DATE_ID ON DBO.WFM_SUBCASE (CLOSE_DATE_ID ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.WS_IDX9_CLOSE_DATE nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.WS_IDX9_CLOSE_DATE ON DBO.WFM_SUBCASE (CLOSE_DATE ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.WS_IDX11_EMPLOYEE_CLOSER nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.WS_IDX11_EMPLOYEE_CLOSER ON DBO.WFM_SUBCASE (EMPLOYEE_CLOSER ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.WC_IDX12_X_REPAIR_CLASS nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE INDEX DBO.WC_IDX12_X_REPAIR_CLASS ON DBO.WFM_SUBCASE (X_REPAIR_CLASS ASC) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
-- Wiedergabe von INDEX DDL für Objekt DBO.WS_PK nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE UNIQUE INDEX DBO.WS_PK ON DBO.WFM_SUBCASE (SUBCASE_ID) 
NOLOGGING 
TABLESPACE "WFMIDXLAR" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 33554432 
  NEXT 33554432 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
)
