/*
 * Create database GCSS.
 * Execute as 'sa'.
 *
 * Create one file for every CPU/core:
 *   HOLMES has got 2 Intel Xeon 5680 with 6 cores * 2 threads = 24 virtual CPUs.
 *   For every filegroup create one file per CPU for data and indexes.
 *
 */

USE master
GO

/*
CREATE DATABASE GCSS
GO
*/

CREATE DATABASE [GCSS]
  ON PRIMARY (NAME = N'GCSS01', FILENAME = N'F:\Data\GCSS01.mdf', SIZE = 10MB, FILEGROWTH = 10MB)
           , (NAME = N'GCSS02', FILENAME = N'F:\Data\GCSS02.ndf', SIZE = 10MB, FILEGROWTH = 10MB)
           , (NAME = N'GCSS03', FILENAME = N'F:\Data\GCSS03.ndf', SIZE = 10MB, FILEGROWTH = 10MB)
           , (NAME = N'GCSS04', FILENAME = N'F:\Data\GCSS04.ndf', SIZE = 10MB, FILEGROWTH = 10MB)
  LOG ON (NAME = N'GCSS_log', FILENAME = N'E:\Logs\GCSS_log.ldf', SIZE = 10GB, FILEGROWTH = 1GB)
GO

ALTER DATABASE [GCSS] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [GCSS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GCSS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GCSS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GCSS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GCSS] SET ARITHABORT OFF 
GO
ALTER DATABASE [GCSS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GCSS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GCSS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GCSS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GCSS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GCSS] SET DISABLE_BROKER 
GO
ALTER DATABASE [GCSS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GCSS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GCSS] SET READ_WRITE 
GO
ALTER DATABASE [GCSS] SET PAGE_VERIFY CHECKSUM  
GO

-- Recovery model
ALTER DATABASE [GCSS] SET RECOVERY SIMPLE 
GO

-- Statistics
ALTER DATABASE [GCSS] SET AUTO_CREATE_STATISTICS OFF 
GO
ALTER DATABASE [GCSS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GCSS] SET AUTO_UPDATE_STATISTICS OFF 
GO
ALTER DATABASE [GCSS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

-- Cursor options
ALTER DATABASE [GCSS] SET CURSOR_DEFAULT LOCAL 
GO
ALTER DATABASE [GCSS] SET CURSOR_CLOSE_ON_COMMIT ON 
GO

-- Enable SNAPSHOT transaction isolation
-- Take care and see help 'ALTER DATABASE SET-Options (T-SQL)' for:
-- Option 'SINGLE_USER' and Option 'AUTO_UPDATE_STATISTICS_ASYNC'
--ALTER DATABASE [GCSS] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
--GO
--ALTER DATABASE [GCSS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
--GO
ALTER DATABASE [GCSS] SET ALLOW_SNAPSHOT_ISOLATION ON
GO
ALTER DATABASE [GCSS] SET READ_COMMITTED_SNAPSHOT ON
GO
-- Reenable async stats?
--ALTER DATABASE [GCSS] SET AUTO_UPDATE_STATISTICS_ASYNC ON
--GO

-- Enable multi user
ALTER DATABASE [GCSS] SET MULTI_USER 
GO

-- Set primary filegroup
USE [GCSS]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY')
  ALTER DATABASE [GCSS] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

-- Add filegroup STAGE1DATAFG
ALTER DATABASE GCSS ADD FILEGROUP STAGE1DATAFG;
ALTER DATABASE GCSS ADD FILEGROUP STAGE1DATAFG;
ALTER DATABASE GCSS ADD FILEGROUP STAGE1DATAFG;
ALTER DATABASE GCSS ADD FILEGROUP STAGE1DATAFG;
GO

ALTER DATABASE GCSS
ADD FILE   (NAME = N'STAGE1DATAFG01', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG01.mdf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG02', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG02.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG03', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG03.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG04', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG04.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG05', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG05.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG06', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG06.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG07', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG07.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG08', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG08.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG09', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG09.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG10', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG10.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG11', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG11.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG12', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG12.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG13', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG13.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG14', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG14.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG15', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG15.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG16', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG16.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG17', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG17.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG18', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG18.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG19', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG19.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG20', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG20.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG21', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG21.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG22', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG22.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG23', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG23.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE1DATAFG24', FILENAME = N'F:\Data\GCSS\STAGE1DATAFG24.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
TO FILEGROUP STAGE1DATAFG
GO

-- Add filegroup STAGE2DATAPxFG
ALTER DATABASE GCSS ADD FILEGROUP STAGE2DATAP1FG;
ALTER DATABASE GCSS ADD FILEGROUP STAGE2DATAP2FG;
ALTER DATABASE GCSS ADD FILEGROUP STAGE2DATAP3FG;
ALTER DATABASE GCSS ADD FILEGROUP STAGE2DATAP4FG;
GO

ALTER DATABASE GCSS
ADD FILE   (NAME = N'STAGE2DATAP1FG01', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG01.mdf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG02', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG02.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG03', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG03.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG04', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG04.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG05', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG05.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG06', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG06.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG07', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG07.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG08', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG08.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG09', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG09.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG10', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG10.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG11', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG11.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG12', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG12.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG13', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG13.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG14', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG14.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG15', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG15.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG16', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG16.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG17', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG17.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG18', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG18.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG19', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG19.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG20', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG20.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG21', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG21.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG22', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG22.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG23', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG23.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP1FG24', FILENAME = N'F:\Data\GCSS\STAGE2DATAP1FG24.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
TO FILEGROUP STAGE2DATAP1FG
GO

ALTER DATABASE GCSS
ADD FILE   (NAME = N'STAGE2DATAP2FG01', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG01.mdf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG02', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG02.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG03', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG03.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG04', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG04.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG05', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG05.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG06', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG06.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG07', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG07.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG08', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG08.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG09', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG09.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG10', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG10.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG11', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG11.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG12', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG12.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG13', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG13.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG14', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG14.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG15', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG15.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG16', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG16.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG17', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG17.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG18', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG18.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG19', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG19.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG20', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG20.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG21', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG21.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG22', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG22.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG23', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG23.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP2FG24', FILENAME = N'F:\Data\GCSS\STAGE2DATAP2FG24.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
TO FILEGROUP STAGE2DATAP2FG
GO

ALTER DATABASE GCSS
ADD FILE   (NAME = N'STAGE2DATAP3FG01', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG01.mdf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG02', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG02.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG03', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG03.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG04', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG04.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG05', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG05.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG06', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG06.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG07', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG07.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG08', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG08.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG09', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG09.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG10', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG10.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG11', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG11.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG12', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG12.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG13', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG13.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG14', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG14.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG15', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG15.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG16', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG16.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG17', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG17.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG18', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG18.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG19', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG19.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG20', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG20.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG21', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG21.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG22', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG22.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG23', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG23.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP3FG24', FILENAME = N'F:\Data\GCSS\STAGE2DATAP3FG24.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
TO FILEGROUP STAGE2DATAP3FG
GO

ALTER DATABASE GCSS
ADD FILE   (NAME = N'STAGE2DATAP4FG01', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG01.mdf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG02', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG02.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG03', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG03.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG04', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG04.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG05', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG05.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG06', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG06.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG07', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG07.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG08', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG08.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG09', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG09.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG10', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG10.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG11', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG11.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG12', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG12.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG13', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG13.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG14', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG14.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG15', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG15.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG16', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG16.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG17', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG17.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG18', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG18.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG19', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG19.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG20', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG20.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG21', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG21.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG22', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG22.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG23', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG23.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2DATAP4FG24', FILENAME = N'F:\Data\GCSS\STAGE2DATAP4FG24.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
TO FILEGROUP STAGE2DATAP4FG
GO

-- Add filegroup STAGE2INDEXPxFG
ALTER DATABASE GCSS ADD FILEGROUP STAGE2INDEXP1FG;
ALTER DATABASE GCSS ADD FILEGROUP STAGE2INDEXP2FG;
ALTER DATABASE GCSS ADD FILEGROUP STAGE2INDEXP3FG;
ALTER DATABASE GCSS ADD FILEGROUP STAGE2INDEXP4FG;
GO

ALTER DATABASE GCSS
ADD FILE   (NAME = N'STAGE2INDEXP1FG01', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG01.mdf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG02', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG02.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG03', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG03.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG04', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG04.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG05', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG05.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG06', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG06.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG07', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG07.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG08', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG08.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG09', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG09.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG10', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG10.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG11', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG11.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG12', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG12.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG13', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG13.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG14', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG14.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG15', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG15.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG16', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG16.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG17', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG17.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG18', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG18.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG19', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG19.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG20', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG20.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG21', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG21.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG22', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG22.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG23', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG23.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP1FG24', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP1FG24.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
TO FILEGROUP STAGE2INDEXP1FG
GO

ALTER DATABASE GCSS
ADD FILE   (NAME = N'STAGE2INDEXP2FG01', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG01.mdf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG02', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG02.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG03', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG03.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG04', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG04.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG05', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG05.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG06', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG06.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG07', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG07.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG08', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG08.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG09', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG09.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG10', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG10.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG11', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG11.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG12', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG12.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG13', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG13.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG14', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG14.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG15', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG15.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG16', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG16.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG17', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG17.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG18', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG18.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG19', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG19.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG20', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG20.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG21', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG21.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG22', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG22.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG23', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG23.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP2FG24', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP2FG24.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
TO FILEGROUP STAGE2INDEXP2FG
GO

ALTER DATABASE GCSS
ADD FILE   (NAME = N'STAGE2INDEXP3FG01', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG01.mdf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG02', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG02.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG03', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG03.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG04', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG04.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG05', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG05.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG06', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG06.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG07', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG07.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG08', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG08.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG09', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG09.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG10', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG10.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG11', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG11.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG12', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG12.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG13', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG13.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG14', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG14.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG15', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG15.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG16', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG16.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG17', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG17.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG18', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG18.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG19', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG19.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG20', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG20.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG21', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG21.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG22', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG22.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG23', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG23.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP3FG24', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP3FG24.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
TO FILEGROUP STAGE2INDEXP3FG
GO

ALTER DATABASE GCSS
ADD FILE   (NAME = N'STAGE2INDEXP4FG01', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG01.mdf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG02', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG02.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG03', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG03.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG04', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG04.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG05', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG05.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG06', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG06.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG07', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG07.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG08', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG08.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG09', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG09.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG10', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG10.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG11', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG11.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG12', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG12.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG13', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG13.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG14', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG14.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG15', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG15.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG16', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG16.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG17', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG17.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG18', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG18.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG19', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG19.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG20', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG20.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG21', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG21.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG22', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG22.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG23', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG23.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
         , (NAME = N'STAGE2INDEXP4FG24', FILENAME = N'F:\Data\GCSS\STAGE2INDEXP4FG24.ndf', SIZE = 1GB, FILEGROWTH = 1GB)
TO FILEGROUP STAGE2INDEXP4FG
GO
