USE GCSS
GO

/*
 * Create a table.
 */
IF OBJECT_ID('stage1.p_create_case_end2end', 'P') IS NOT NULL 
    DROP PROCEDURE stage1.p_create_case_end2end
GO
CREATE PROCEDURE stage1.p_create_case_end2end(
	@schema_name   NVARCHAR(255) = 'stage1'
	, @table_name  NVARCHAR(255)
)
AS
BEGIN
	-- No row count
	SET NOCOUNT ON
	-- Rollback running transactions automatically in case of failure
	SET XACT_ABORT ON
	-- Create table
	EXEC stage1.p_create_table @schema_name = @schema_name, @table_name = @table_name, @table_def = ' (
		  CASE_ID NVARCHAR(90) NOT NULL 
		, ACCOUNTABILITY_ID NVARCHAR(90) NOT NULL 
		, CALL_TYPE NVARCHAR(240) 
		, CASE_TITLE NVARCHAR(240) 
		, CONDITION_CODE_VALUE NVARCHAR(90) 
		, CONTRACT_ID NVARCHAR(90) 
		, NAME NVARCHAR(240) 
		, ADDRESS NVARCHAR(600) 
		, ADDRESS2 NVARCHAR(600) 
		, ZIP_CODE NVARCHAR(90) 
		, CITY NVARCHAR(120) 
		, COUNTRY NVARCHAR(120) 
		, CONTACT_FIRST_NAME NVARCHAR(90) 
		, CONTACT_LAST_NAME NVARCHAR(90) 
		, CALLER_PHONE NVARCHAR(90) 
		, CONTACT_E_MAIL NVARCHAR(240) 
		, PRODUCT_FAMILY NVARCHAR(120) 
		, PRODUCT NVARCHAR(90) 
		, PRODUCT_DESCRIPTION NVARCHAR(765) 
		, PRODUCT_LINE NVARCHAR(90) 
		, SERIAL_NUMBER NVARCHAR(90) 
		, SERVICE_NOTE_NUMBER NVARCHAR(60) 
		, WARR_PROOF_PURCHASE DATETIME2
		, WARR_CODE NVARCHAR(6) 
		, WARR_DESC NVARCHAR(240) 
		, WARR_RESP NVARCHAR(30) 
		, CR_DATE_GMT DATETIME2
		, CR_DATE_CUST DATETIME2
		, CR_LOGIN_NAME NVARCHAR(120) 
		, CR_WORK_GROUP NVARCHAR(240) 
		, CR_RESPONSE_CENTER NVARCHAR(120) 
		, OW_LOGIN_NAME NVARCHAR(120) 
		, OW_RESPONSE_CENTER NVARCHAR(120) 
		, WARRANTY_STATUS NVARCHAR(45) 
		, DATE_MODIFIED DATETIME2
		, EMPLOYEE_OWNER NUMERIC(38) 
		, ENTRY_POINT NVARCHAR(120) 
		, DELIVERY_ALTERNATIVE NVARCHAR(120)
	)'
END
GO
