USE GCSS
GO

CREATE TABLE stage2.HP_COUNTRY_DM (
	  COUNTRY_ID NUMERIC(10, 0) NOT NULL 
	, COUNTRY_CODE NUMERIC(10, 0) 
	, X_ISO_CODE NVARCHAR(6) 
	, X_SUPER_REGION NVARCHAR(12) 
	, NAME NVARCHAR(120) 
	, CONSTRAINT HCD_PK PRIMARY KEY 
	  (
		COUNTRY_ID 
	  )
) ON [PRIMARY]
GO
