USE GCSS
GO

CREATE TABLE stage2.HP_SV_DLVR_DM (
	  HP_SV_DLVR_ID NUMERIC(10, 0) NOT NULL 
	, CASE_ID NVARCHAR(90) NOT NULL 
	, SUBCASE_ID NVARCHAR(90) 
	, X_SERVICE_LOCATION NVARCHAR(240)
	, X_ADDRESS NVARCHAR(600) 
	, X_ADDRESS_2 NVARCHAR(600) 
	, X_CITY NVARCHAR(90) 
	, X_STATE NVARCHAR(120) 
	, X_ZIPCODE NVARCHAR(60) 
	, X_ISO_COUNTRY_CODE NVARCHAR(6) 
	, X_CONTACT_PHONE NVARCHAR(75) 
	, ENGINEER_FIRST_NAME NVARCHAR(90) 
	, ENGINEER_LAST_NAME NVARCHAR(90) 
	, DATE_MODIFIED DATETIME2
	, X_CONTACT_FIRST_NAME NVARCHAR(90) 
	, X_CONTACT_LAST_NAME NVARCHAR(90) 
	, X_CONTACT_ALT_PHONE NVARCHAR(75) 
	, X_CONTACT_EMAIL NVARCHAR(240) 
	, X_CONTACT_PREF_LANG NVARCHAR(60) 
	, X_ALT_CONTACT_FIRST_NAME NVARCHAR(90) 
	, X_ALT_CONTACT_LAST_NAME NVARCHAR(90) 
	, X_ALT_CONTACT_PHONE NVARCHAR(75) 
	, X_ALT_CONTACT_ALT_PHONE NVARCHAR(75) 
	, X_ALT_CONTACT_EMAIL NVARCHAR(240) 
	, X_ALT_CONTACT_PREF_LANG NVARCHAR(60) 
) ON stage2_date_ps (DATE_MODIFIED)
GO

CREATE UNIQUE CLUSTERED INDEX HSDD_PK
ON stage2.HP_SV_DLVR_DM (HP_SV_DLVR_ID, DATE_MODIFIED)
ON stage2_date_ps (DATE_MODIFIED)
GO
