USE GCSS
GO

CREATE TABLE stage2.ONSITE_LOG_DM (
	  ONSITE_LOG_ID NUMERIC(10, 0) NOT NULL 
	, ACCOUNTABILITY_ID NVARCHAR(90) 
	, CASE_ID NVARCHAR(90) 
	, CASE_SUBCASE NVARCHAR(30) 
	, EMPLOYEE_TABLE_ID NUMERIC(10, 0) NOT NULL 
	, DATE_MODIFIED DATETIME2
	, NOTES NVARCHAR(4000) 
	, PERF_BY NVARCHAR(90) 
) ON stage2_date_ps (DATE_MODIFIED)
GO

CREATE UNIQUE CLUSTERED INDEX OLD_PK
ON stage2.ONSITE_LOG_DM (ONSITE_LOG_ID, DATE_MODIFIED)
ON stage2_date_ps (DATE_MODIFIED)
GO
