USE GCSS
GO

CREATE TABLE stage2.SUBCASE_END2END (
	  SUBCASE_ID NVARCHAR(90) NOT NULL 
	, ACCOUNTABILITY_ID NVARCHAR(90) 
	, CONDITION_CODE_VALUE NVARCHAR(240) 
	, CR_DATE_GMT DATE 
	, CR_LOGIN_NAME NVARCHAR(120) 
	, CR_WORK_GROUP NVARCHAR(240) 
	, OW_WORK_GROUP NVARCHAR(240) 
	, OW_RESPONSE_CENTER NVARCHAR(120) 
	, CL_LOGIN_NAME NVARCHAR(120) 
	, DATE_MODIFIED DATETIME2
	, DELIVERY_ALTERNATIVE NVARCHAR(120) 
) ON stage2_date_ps (DATE_MODIFIED)
GO

CREATE UNIQUE CLUSTERED INDEX SE2E_PK
ON stage2.SUBCASE_END2END (SUBCASE_ID, DATE_MODIFIED)
ON stage2_date_ps (DATE_MODIFIED)
GO
