USE GCSS
GO

CREATE TABLE stage2.WFM_CASE (
	  ACCOUNTABILITY_ID  NVARCHAR(90) NOT NULL
	, CASE_ID            NVARCHAR(90) NOT NULL
	, CUSTOMER_SITE_ID   NVARCHAR(240)
	, DATE_MODIFIED      DATETIME2
	, SELECTED_OFFER_ID  NUMERIC(10, 0)
) ON stage2_date_ps (DATE_MODIFIED)
GO

CREATE UNIQUE CLUSTERED INDEX WC_PK
ON stage2.WFM_CASE (ACCOUNTABILITY_ID, DATE_MODIFIED)
ON stage2_date_ps (DATE_MODIFIED)
GO
