USE GCSS
GO

CREATE TABLE stage2.WFM_SUBCASE (
	  SUBCASE_ID NVARCHAR(90) NOT NULL 
	, SUBCASE_TRACKING_ID NVARCHAR(90) NOT NULL 
	, CASE_ACCOUNTABILITY_ID NVARCHAR(90) 
	, ACTION_TYPE NVARCHAR(90) 
	, OPEN_DATE DATETIME2
	, DATE_MODIFIED DATETIME2
	, X_REPAIR_CLASS NVARCHAR(6) 
	, X_OTC NVARCHAR(60) 
	, PARTNER_CO_NAME NVARCHAR(240) 
	, DELIVERY_ALTERNATIVE NVARCHAR(120) 
) ON stage2_date_ps (DATE_MODIFIED)
GO

CREATE UNIQUE CLUSTERED INDEX WS_PK
ON stage2.WFM_SUBCASE (SUBCASE_ID, DATE_MODIFIED)
ON stage2_date_ps (DATE_MODIFIED)
GO
