USE GCSS
GO

CREATE TABLE stage2.HP_PARTS_INFO_DM (
	  ACCOUNTABILITY_ID NVARCHAR(90) NOT NULL 
	, SUBCASE_TRACKING_ID NVARCHAR(90) NOT NULL 
	, PARTS_INFO_ID NUMERIC(38) NOT NULL 
	, ORDER_NUMBER NVARCHAR(48) 
	, SELECTED_QUANTITY NUMERIC(38) 
	, PART_NUMBER NVARCHAR(120) 
	, PART_DESC NVARCHAR(480) 
	, CURRENCY NVARCHAR(30) 
	, LIST_PRICE NUMERIC(38, 2) 
	, SOURCE_LOCATION NVARCHAR(120) 
	, DATE_MODIFIED DATETIME2 NOT NULL 
	, X_FAILURE_CD NVARCHAR(12) 
	, X_SERIAL_NUMBER NVARCHAR(90)
	, X_PART_STATUS NVARCHAR(60) 
	, X_PART_USAGE NVARCHAR(54) 
	, X_TRACKING_NUMBER NVARCHAR(120) 
	, X_LOGISTICS_LINE_NUMBER NUMERIC(10, 0) 
	, CASE_ID NVARCHAR(90) 
	, HP_PART_ORDER_ID NUMERIC(10, 0) 
	, X_RETURNABLE_CD NVARCHAR(3) 
) ON stage2_date_ps (DATE_MODIFIED)
GO

CREATE UNIQUE CLUSTERED INDEX HPID_PK
ON stage2.HP_PARTS_INFO_DM (ACCOUNTABILITY_ID, PARTS_INFO_ID, SUBCASE_TRACKING_ID, DATE_MODIFIED)
ON stage2_date_ps (DATE_MODIFIED)
GO
