USE GCSS
GO

CREATE TABLE stage2.PHONE_LOG_DM (
	  ACCOUNTABILITY_ID NVARCHAR(90) 
	, CREATE_DATE DATETIME2 NOT NULL 
	, CASE_ID NVARCHAR(90) NOT NULL 
	, ACTION_TYPE NVARCHAR(120) 
	, CASE_SUBCASE NVARCHAR(30) 
	, EMPLOYEE_ID NUMERIC(38) 
	, NOTES NVARCHAR(4000) 
	, WORK_GROUP NVARCHAR(240) 
	, PHONE_LOG_ID NUMERIC(10, 0) 
	, INTERNAL NVARCHAR(765) 
) ON stage2_date_ps (CREATE_DATE)
GO
/*
CREATE UNIQUE CLUSTERED INDEX xxx
ON stage2.PHONE_LOG_DM (ONSITE_LOG_ID, CREATE_DATE)
ON stage2_date_ps (DATE_MODIFIED)
GO
*/
