USE GCSS
GO

CREATE TABLE stage2.HP_PART_ORDER_DM (
	  HP_PART_ORDER_ID NUMERIC(10, 0) NOT NULL 
	, SUBCASE_ID NVARCHAR(90) NOT NULL 
	, CASE_ID NVARCHAR(90) 
	, X_ORDER_ID NVARCHAR(120) 
	, X_ORDER_NUMBER NVARCHAR(120) 
	, X_SHIP_ADDRESS NVARCHAR(600) 
	, X_SHIP_ADDRESS2 NVARCHAR(600) 
	, X_SHIP_CITY NVARCHAR(90) 
	, X_SHIP_COUNTRY NVARCHAR(120) 
	, X_SHIP_STATE NVARCHAR(120) 
	, X_SHIP_ZIPCODE NVARCHAR(60) 
	, X_COMPANY_NAME NVARCHAR(240) 
	, X_LOGISTICS_SYSTEM NVARCHAR(60) 
	, X_CONTACT_ALT_PHONE NVARCHAR(75) 
	, X_CONTACT_FIRST_NAME NVARCHAR(90) 
	, X_CONTACT_LAST_NAME NVARCHAR(90) 
	, X_CONTACT_PHONE NVARCHAR(75) 
	, DATE_MODIFIED DATETIME2
	, X_SHIP_ISO_COUNTRY_CODE NVARCHAR(6) 
	, X_CONTACT_FAX_NUMBER NVARCHAR(60) 
	, HP_PART_ORDER_REASON NVARCHAR(240) 
) ON stage2_date_ps (DATE_MODIFIED)
GO

CREATE UNIQUE CLUSTERED INDEX HPOD_PK
ON stage2.HP_PART_ORDER_DM (HP_PART_ORDER_ID, DATE_MODIFIED)
ON stage2_date_ps (DATE_MODIFIED)
GO
