USE GCSS
GO

CREATE TABLE stage2.EMPLOYEE_TABLE_DM (
	  EMPLOYEE_TABLE_ID NUMERIC(38) NOT NULL 
	, EMPLOYEE_ID NVARCHAR(30) 
	, LOCATION NVARCHAR(240) 
	, LOGIN_NAME NVARCHAR(120) 
	, REGION NVARCHAR(90) 
	, RESPONSE_CENTER NVARCHAR(120) 
	, DATE_ADDED DATETIME2
	, DATE_MODIFIED DATETIME2
	, EMPLOYEE_PHONE NVARCHAR(75)
	, EMPLOYEE_EMAIL NVARCHAR(240)
) ON stage2_date_ps (DATE_MODIFIED)
GO

CREATE UNIQUE CLUSTERED INDEX ETD_PK
ON stage2.EMPLOYEE_TABLE_DM (EMPLOYEE_TABLE_ID, DATE_MODIFIED)
ON stage2_date_ps (DATE_MODIFIED)
GO
